# Generated by Django 2.1.3 on 2018-11-29 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=10, unique=True)),
                ('sensor_1', models.PositiveIntegerField(default=0)),
                ('sensor_2', models.PositiveIntegerField(default=0)),
                ('sensor_3', models.PositiveIntegerField(default=0)),
                ('sensor_4', models.PositiveIntegerField(default=0)),
                ('last_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_1', models.PositiveIntegerField(default=0)),
                ('sensor_2', models.PositiveIntegerField(default=0)),
                ('sensor_3', models.PositiveIntegerField(default=0)),
                ('sensor_4', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app_backend.Farm')),
            ],
        ),
    ]
