# Generated by Django 2.1.3 on 2018-12-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_auto_20181129_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='sensor_1',
            new_name='sensor_light',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='sensor_2',
            new_name='sensor_temp_air',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='sensor_3',
            new_name='sensor_temp_water',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='sensor_1',
            new_name='sensor_light',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='sensor_2',
            new_name='sensor_temp_air',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='sensor_3',
            new_name='sensor_temp_water',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='sensor_4',
        ),
        migrations.RemoveField(
            model_name='history',
            name='sensor_4',
        ),
        migrations.AddField(
            model_name='farm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
