# Generated by Django 2.1.4 on 2018-12-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_auto_20181205_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='farm',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='sensor_wetness',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='sensor_wetness',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
