# Generated by Django 2.1.4 on 2018-12-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0005_auto_20181209_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='name',
        ),
    ]
