# Generated by Django 2.1.4 on 2018-12-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0006_remove_farm_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='seed',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
