# Generated by Django 2.1.4 on 2018-12-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0007_auto_20181214_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('date',)},
        ),
    ]
